site_name: jml-extract
plugins:
  - search
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - attr_list
  - toc:
      permalink: true
  - markdown_aafigure:
      format: svg
  - markdown_blockdiag:
      format: svg
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

docs_dir: 'pages/'

theme:
  name: material

    #extra:
    # repo_icon: gitlab
    #repo_type: gitlab
    #repo_name: key-docs
    #repo_url: https://git.key-project.org/key/key-docs/
